### ISSUE TITLE
only errors

### ISSUE THREAD

**Issue by uselessnn** [LIL-JABA/valchecker#34]
(2023-01-07 23:43:04.869895) Traceback (most recent call last):
  File "C:\Users\user\Desktop\valchecker-main\src\codeparts\auth.py", line 111, in auth
    asyncio.run(auth.authorize(username,password,proxy=proxy))
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\valchecker-main\src\codeparts\riot_auth\auth.py", line 193, in authorize
    async with session.post(
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 434, in _request
    proxy = URL(proxy)
            ^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\yarl\_url.py", line 154, in __new__
    raise TypeError("Constructor parameter should be str")
TypeError: Constructor parameter should be str

**Comment by LIL-JABA** [comment]
don't use proxies now. they do not work
