### ISSUE TITLE
 nie działa

### ISSUE THREAD

**Issue by ZEROmagicQ** [LIL-JABA/valchecker#5]
chcę użyć pierwszej metody, ale daje błąd:
Traceback (most recent call last):
  File "C:\Users\ma841\Desktop\New folder (3)\valchecker\main.py", line 226, in <module>
    pr.start()
  File "C:\Users\ma841\Desktop\New folder (3)\valchecker\main.py", line 65, in start
    self.main(redirect=False)
  File "C:\Users\ma841\Desktop\New folder (3)\valchecker\main.py", line 177, in main
    region,level=sys.get_region(acctoken)
TypeError: system.get_region() missing 2 required positional arguments: 'ent' and 'uuid'

**Comment by ZEROmagicQ** [comment]
chwała kapibary

**Comment by LIL-JABA** [comment]
fixed
