### ISSUE TITLE
error

### ISSUE THREAD

**Issue by KayRaamAMaL** [LIL-JABA/valchecker#69]
Traceback (most recent call last):
  File "C:\Users\simse\OneDrive\Masaüstü\valchecker-main\src\main.py", line 20, in <module>
    import checker
  File "C:\Users\simse\OneDrive\Masaüstü\valchecker-main\src\checker.py", line 61
    match account.code:
          ^
SyntaxError: invalid syntax
Press any key to continue . . .

pls help

**Comment by LIL-JABA** [comment]
https://liljaba1337.gitbook.io/valchecker/installation/python
